# Generated by Django 3.0.4 on 2020-04-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numpages',
            new_name='num_pages',
        ),
    ]
